cypress/e2e/admin-service/e2ejourneys-AdminServ/e2e-AddServ-001.spec.js
=> deletes spaces

cypress/e2e/admin-service/e2ejourneys-AdminServ/e2e-AddServ-002.spec.js, cypress/e2e/admin-service/e2ejourneys-AdminServ/e2e-AddServ-009.spec.js, cypress/e2e/admin-service/e2ejourneys-AdminServ/e2e-ManServ-001.spec.js, cypress/e2e/admin-service/e2ejourneys-AdminServ/e2e-ManServ-004.spec.js, cypress/e2e/admin-service/e2ejourneys-AdminServ/e2e-ManServ-005.spec.js, cypress/e2e/admin-service/e2ejourneys-AdminServ/e2e-ManServ-006.spec.js, cypress/e2e/admin-service/e2ejourneys-AdminServ/e2e-ManServ-007.spec.js, cypress/e2e/admin-service/e2ejourneys-AdminServ/e2e-ManServ-008.spec.js, cypress/e2e/admin-service/e2ejourneys-AdminServ/e2e-ManServ-009.spec.js, cypress/e2e/admin-service/e2ejourneys-AdminServ/e2e-ManServ-010.spec.js, cypress/e2e/admin-service/e2ejourneys-AdminServ/e2e-ManServ-011.spec.js, cypress/support/commands.js
=> Adds Admin Service e2e journeys

cypress/e2e/admin-service/e2ejourneys-AdminServ/e2e-ManServ-005.spec.js, cypress/e2e/admin-service/e2ejourneys-AdminServ/e2e-ManServ-006.spec.js, cypress/e2e/admin-service/e2ejourneys-AdminServ/e2e-ManServ-007.spec.js, cypress/e2e/admin-service/e2ejourneys-AdminServ/e2e-ManServ-008.spec.js, cypress/e2e/admin-service/e2ejourneys-AdminServ/e2e-ManServ-009.spec.js, cypress/e2e/admin-service/e2ejourneys-AdminServ/e2e-ManServ-010.spec.js, cypress/e2e/admin-service/e2ejourneys-AdminServ/e2e-ManServ-011.spec.js, cypress/e2e/admin-service/e2ejourneys-AdminServ/e2e-dfeBranding.spec.js, cypress/e2e/referral-service/e2ejourneys-RefServ/e2e-RefService-001.spec.js, cypress/e2e/referral-service/e2ejourneys-RefServ/e2e-RefService-002.spec.js, cypress/e2e/referral-service/e2ejourneys-RefServ/e2e-RefService-003.spec.js, cypress/e2e/referral-service/e2ejourneys-RefServ/e2e-RefService-004.spec.js, cypress/e2e/referral-service/e2ejourneys-RefServ/e2e-RefService-005.spec.js, cypress/e2e/referral-service/e2ejourneys-RefServ/e2e-RefService-006.spec.js, cypress/e2e/referral-service/mobile-e2ejourney-RefServ.spec.js, cypress/e2e/referral-service/smokeTest-RefService.spec.js, cypress/reports/html/.jsons/mochawesome.json, cypress/support/commands.js, cypress/support/referralCommands.js
=> Refactor Regression Admin-UI

.github/workflows/dev-referralUi-regression.yml
=> GHA referralui yml update

.github/workflows/dev-adminUi-regression.yml, .github/workflows/dev-referralUi-regression.yml
=> GHA schedule adds to admin tests & referral tests

.github/workflows/dev-adminUi-regression.yml, .github/workflows/dev-referralUi-regression.yml
=> fix GHA yml for referral + admin services

cypress/e2e/01-referral-service/e2ejourneys-RefServ/e2e-RefService002-category2.spec.js, cypress/e2e/01-referral-service/e2ejourneys-RefServ/e2e-RefService003-category3.spec.js, cypress/e2e/01-referral-service/e2ejourneys-RefServ/e2e-RefService004-category4.spec.js, cypress/e2e/01-referral-service/e2ejourneys-RefServ/e2e-RefService005-category5.spec.js, cypress/e2e/01-referral-service/frontend-RefServ/footerLinks.spec.js, cypress/support/referralCommands.js
=> Referral Service - footer links tests added

.github/workflows/test-referralUi-regression.yml
=> GHA referral-ui fix test url

cypress/e2e/01-referral-service/e2ejourneys-RefServ/e2e-RefService008-age.spec.js, cypress/e2e/01-referral-service/e2ejourneys-RefServ/e2e-RefService010-language.spec.js, cypress/e2e/01-referral-service/e2ejourneys-RefServ/e2e-RefService012-detailsPage.spec.js, cypress/e2e/01-referral-service/frontend-RefServ/pageLinks.spec.js, cypress/support/referralCommands.js, package.json
=> Refactor regression - ref serv

.github/workflows/test-adminUi-regression.yml
=> GHA admin-ui change url

cypress/e2e/01-referral-service/PageSpecs/safeguardingpage.spec.js, cypress/support/commands.js
[FHG-2848](https://dfedigital.atlassian.net/browse/FHG-2848)
=> FHG-2848 Add tests for safeguarding page

cypress/e2e/01-referral-service/PageSpecs/consentPage.spec.js, cypress/support/commands.js
[FHG-2850](https://dfedigital.atlassian.net/browse/FHG-2850)
- added tests in a new spec file consentPage.spec.js
- modified commads.js
=> FHG-2850 Add tests for consent page

cypress/e2e/01-referral-service/PageSpecs/consentPage.spec.js, cypress/e2e/01-referral-service/PageSpecs/familyContactPage.spec.js, cypress/support/commands.js
[FHG-2858](https://dfedigital.atlassian.net/browse/FHG-2858)
- added new tests for contact name page - familyContactPage.spec.js
- added helper commands in commands.js
=> FHG-2858 Add tests for family contact name page

cypress/e2e/01-referral-service/PageSpecs/cannotConnectFamilyPage.spec.js
[FHG-2853](https://dfedigital.atlassian.net/browse/FHG-2853)
- added tests for cannot connect family to service page - cannotConnectFamilyPage.spec.js
=> FHG-2853 Add tests for cannot connect to service page

cypress/e2e/01-referral-service/PageSpecs/cannotConnectFamilyPage.spec.js, cypress/e2e/01-referral-service/PageSpecs/consentPage.spec.js, cypress/e2e/01-referral-service/PageSpecs/familyContactPage.spec.js, cypress/e2e/01-referral-service/PageSpecs/reasonForConnectionPage.spec.js, cypress/e2e/01-referral-service/PageSpecs/safeguardingpage.spec.js, cypress/support/commands.js
[FHG-2860](https://dfedigital.atlassian.net/browse/FHG-2860)
-  Added tests for reason for connection request page - reasonForConnectionPage.spec.js
- modified tests for content changes in other pages
- Added reusable support methods in commands.js
=> FHG-2860 Add tests for reason for connection page

cypress.config.js, cypress/e2e/01-referral-service/PageSpecs/cannotConnectFamilyPage.spec.js, cypress/e2e/01-referral-service/PageSpecs/consentPage.spec.js, cypress/e2e/01-referral-service/PageSpecs/familyContactPage.spec.js, cypress/e2e/01-referral-service/PageSpecs/howCanServiceContactPage.spec.js, cypress/e2e/01-referral-service/PageSpecs/reasonForConnectionPage.spec.js, cypress/e2e/01-referral-service/PageSpecs/safeguardingpage.spec.js, cypress/support/commands.js
[FHG-2862](https://dfedigital.atlassian.net/browse/FHG-2862)
- Added tests for contact methods page - howCanServiceContactPage.spec.js
- Added support comands
- Modified other page specs to use test url
=> FHG-2862 Add tests for contact methods page

cypress/e2e/01-referral-service/PageSpecs/consentPage.spec.js, cypress/e2e/01-referral-service/PageSpecs/emailAddressPage.spec.js, cypress/e2e/01-referral-service/PageSpecs/familyContactPage.spec.js, cypress/support/commands.js
[FHG-2866](https://dfedigital.atlassian.net/browse/FHG-2866)
-  Added tests for email address page - emailAddressPage.spec.js
=> FHG-2866 Add tests for email address page

cypress/e2e/01-referral-service/PageSpecs/consentPage.spec.js, cypress/e2e/01-referral-service/PageSpecs/emailAddressPage.spec.js, cypress/e2e/01-referral-service/PageSpecs/familyContactPage.spec.js, cypress/e2e/01-referral-service/PageSpecs/howCanServiceContactPage.spec.js, cypress/e2e/01-referral-service/PageSpecs/reasonForConnectionPage.spec.js
- Amended error scenarios to continue the journey
=> Improvements to error scenarios

cypress/e2e/01-referral-service/PageSpecs/telephoneNumberPage.spec.js
[FHG-2868](https://dfedigital.atlassian.net/browse/FHG-2868)
-  Added tests for telephone number page
=> FHG-2868 Add tests for telephone number page

cypress/e2e/01-referral-service/PageSpecs/telephoneNumberPage.spec.js, cypress/e2e/01-referral-service/PageSpecs/textMessagePage.spec.js
[FHG-2876](https://dfedigital.atlassian.net/browse/FHG-2876)
- Added tests for text message page
=> FHG-2876 Add tests for text message page

.github/workflows/test-adminUi-regression.yml, .github/workflows/test-referralUi-regression.yml, cypress/e2e/01-referral-service/PageSpecs/cannotConnectFamilyPage.spec.js, cypress/e2e/01-referral-service/PageSpecs/consentPage.spec.js, cypress/e2e/01-referral-service/PageSpecs/emailAddressPage.spec.js, cypress/e2e/01-referral-service/PageSpecs/familyContactPage.spec.js, cypress/e2e/01-referral-service/PageSpecs/howCanServiceContactPage.spec.js, cypress/e2e/01-referral-service/PageSpecs/reasonForConnectionPage.spec.js, cypress/e2e/01-referral-service/PageSpecs/safeguardingpage.spec.js, cypress/e2e/02-admin-service/smokeTest-AdminService.spec.js, cypress/support/commands.js, cypress/support/referralCommands.js, package.json
=> minor fixes 

cypress/e2e/01-referral-service/PageSpecs/telephoneNumberPage.spec.js, cypress/e2e/01-referral-service/PageSpecs/textMessagePage.spec.js
=> Adds loginPage to tests

cypress/e2e/01-referral-service/PageSpecs/addressPage.spec.js, cypress/e2e/01-referral-service/PageSpecs/telephoneNumberPage.spec.js, cypress/e2e/01-referral-service/PageSpecs/textMessagePage.spec.js, cypress/support/commands.js, cypress/support/referralCommands.js
[FHG-2878](https://dfedigital.atlassian.net/browse/FHG-2878)
- Added tests for address page - addressPage.spec.js
- Modified custom commands
=> FHG-2878 Add tests for address page

cypress/e2e/01-referral-service/PageSpecs/howCanServiceEngageWithFamily.spec.js
[FHG-2880](https://dfedigital.atlassian.net/browse/FHG-2880)
- Added tests for 'How can the service engage with the family?' page
=> FHG-2880 Add tests for how the service engages with family page

cypress/e2e/01-referral-service/PageSpecs/checkDetailsPage.spec.js, cypress/support/commands.js
[FHG-2884](https://dfedigital.atlassian.net/browse/FHG-2884)
- Added tests for details page - checkDetailsPage.spec.js
- Added custom commands in commands.js
=> FHG-2884 Add tests for details page

cypress/e2e/01-referral-service/PageSpecs/safeguardingpage.spec.js, cypress/support/commands.js
[FHG-3538](https://dfedigital.atlassian.net/browse/FHG-3538)
- Amended error message text
- Change continue link to a button
=> FHG-3538 Amend tests for button changes

cypress/e2e/01-referral-service/ProfessionalFormPageSpecs/howCanServiceContactProfessionalPage.spec.js, cypress/support/commands.js
[FHG-3669](https://dfedigital.atlassian.net/browse/FHG-3669)
- Added tests for 'How can the service contact you for more details about this request?' page
=> FHG-3669 Added tests for professional contact details

cypress/e2e/01-referral-service/ProfessionalFormPageSpecs/cannotConnectFamilyPage.spec.js, cypress/e2e/01-referral-service/ProfessionalFormPageSpecs/checkDetailsPage.spec.js, cypress/e2e/01-referral-service/ProfessionalFormPageSpecs/privacyStatementPage.spec.js, cypress/e2e/01-referral-service/ProfessionalFormPageSpecs/sharePrivacyStatementPage.spec.js
[FHG-3670](https://dfedigital.atlassian.net/browse/FHG-3670)
[FHG-3671](https://dfedigital.atlassian.net/browse/FHG-3671)
[FHG-3725](https://dfedigital.atlassian.net/browse/FHG-3725)
[FHG-3727](https://dfedigital.atlassian.net/browse/FHG-3727)
- Added tests for privacy statement and check details pages
=> Added tests for professional journey new pages

cypress/e2e/01-referral-service/ProfessionalFormPageSpecs/addressPage.spec.js, cypress/e2e/01-referral-service/ProfessionalFormPageSpecs/checkDetailsPage.spec.js, cypress/e2e/01-referral-service/ProfessionalFormPageSpecs/confirmationPage.spec.js, cypress/e2e/01-referral-service/ProfessionalFormPageSpecs/consentPage.spec.js, cypress/e2e/01-referral-service/ProfessionalFormPageSpecs/emailAddressPage.spec.js, cypress/e2e/01-referral-service/ProfessionalFormPageSpecs/familyContactPage.spec.js, cypress/e2e/01-referral-service/ProfessionalFormPageSpecs/howCanServiceContactPage.spec.js, cypress/e2e/01-referral-service/ProfessionalFormPageSpecs/howCanServiceEngageWithFamily.spec.js, cypress/e2e/01-referral-service/ProfessionalFormPageSpecs/reasonForConnectionPage.spec.js, cypress/e2e/01-referral-service/ProfessionalFormPageSpecs/safeguardingpage.spec.js, cypress/e2e/01-referral-service/ProfessionalFormPageSpecs/telephoneNumberPage.spec.js, cypress/e2e/01-referral-service/ProfessionalFormPageSpecs/textMessagePage.spec.js, cypress/support/commands.js
[FHG-3728](https://dfedigital.atlassian.net/browse/FHG-3728)
- Amended content on reason for connection request page
- Fixed professional form page tests
=> FHG-3728 Amend content; fix professional form page tests

cypress/e2e/01-referral-service/ProfessionalFormPageSpecs/howCanServiceEngageWithFamily.spec.js
[FHG-3885](https://dfedigital.atlassian.net.mcas.ms/browse/FHG-3885)
- Amend content on How can service engage with the family page
=> FHG-3885 Amend content on 'How can service engage with the family' page

cypress.config.js, package.json
FHG-4689 - cypress integration to ADO pipelines
=> Azure test

.github/dependabot.yml
Added dependabot.yml file to check for version updates
=> Dependabot version

.github/workflows/test-referralUi-regression.yml
https://dfedigital.atlassian.net/browse/FHB-854
I have commented out the github workflows so the cypress tests do not run against test 1 whilst pen test is occurring.
=> FHB-854 Disabled automated test run
